when we join and put a condition in sql we do it together in python we have a choice to filter first or join first!!

in exam we may get an option to do sql and/or python

numpy can be much faster than Python's native list and dictionary types when you only need to store and operate on numerical data.

In [1]:
import pandas as pd
import numpy as np

Spare means that most of the matrix is empty

Can be stored as triplets that are together (1,2,1) (1,3,1) (3,1,1)

Or 
Coordinate format (COO) !!
rows = [1,1,3]
cls = [2,3,1]
values = [1,1,1]
reqyures 3nnz to store the matrix

Or Compressed spare format (CSR)
Reduction due to using rowptr
requires 2nnz + n to store matrix

In [2]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
b = np.eye(3, dtype = int)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
Z= np.array([[0,1,2,3,4,5],
             [10,11,12,13,14,15],
             [20,21,22,23,24,25],
             [30,31,32,33,34,35],
             [40,41,42,43,44,45],
             [50,51,52,53,54,55]])

In [5]:
Z[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

To help save memory, when you slice a Numpy array, you are actually creating a view into that array. That means modifications through the view will modify the original array.

If you copy then u can do what you want

In [6]:
Z1 = Z.copy()

In [7]:
Z.ndim

2

In [8]:
Z.shape

(6, 6)

In [9]:
len(Z)

6

In [10]:
C1 = [[0, 1, 2, 3],
      [4, 5, 6, 7],
      [8, 9, 10, 11]]

C2 = [[12, 13, 14, 15],
      [16, 17, 18, 19],
      [20, 21, 22, 23]]

C = np.array([C1, C2])

print(C)
print(C.ndim)
print(C.shape)
print(len (C))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)
2


In [11]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a = np.array([12,423,4363,2,3424])
b = [0,2,3]
a[b]

array([  12, 4363,    2])

In [17]:
np.max(a)

4363

In [18]:
np.min(a)

2

In [19]:
np.sum(a)

8224

In [20]:
np.mean(a)

1644.8

In [21]:
np.std(a)

1866.1075424530068

In [22]:
np.abs(a)

array([  12,  423, 4363,    2, 3424])

In [23]:
#element wise
#A*B

In [24]:
#matrix product
# A.dot(B)
# A @ B

In [25]:
# # Convert values into Numpy arrays in column-major order
# A_np = np.reshape(A_py, (n, n), order='F')
# x_np = np.reshape(x_py, (n, 1), order='F')
# A_np